### ISSUE TITLE
Use the JSON interface instead of the recursive Bean->Map

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/twitter-plugin#3]

**Comment by mpenet** [comment]
I believe this should be fixed by https://github.com/onyx-platform/onyx-twitter/commit/9996fd38f43710e3ced4817f182d18848c6c2a3b (using RawStreamListener)

**Comment by MichaelDrogalis** [comment]
Yep, looks good. :)

**Comment by MichaelDrogalis** [comment]
Out on beta-11.
